Repository Oomaxime/DesignSystem, pull requests merged in 2025-01, with the labels that each got.

#11 7 storybook cicd
  .github/workflows/chromatic.yml
  package.json
Labels: in progress

#17 10 creation du formulaire de profil
  src/App.jsx
  src/assets/images/illustre_auth_form.avif
  src/assets/images/illustre_auth_form.png
  src/assets/images/illustre_auth_form.webp
  src/assets/images/main_image.jpg
  src/components/auth/FormProfil.jsx
  src/components/ui/Button.jsx
  src/components/ui/Form.jsx
  src/components/ui/Icon.jsx
  src/components/ui/Input.jsx
  src/components/ui/Text.jsx
  src/layouts/FormLayout.jsx
  src/pages/ConnexionForm.jsx
  src/pages/ForgotPasswordForm.jsx
  src/stories/components/form/Form.stories.jsx
  src/stories/components/ui/Button.stories.jsx
  src/stories/components/ui/Icon.stories.jsx
  src/stories/components/ui/Input.stories.jsx
  src/stories/test/FirstButton.stories.jsx
  src/stories/test/TestButton.stories.jsx
  src/stories/test/TestInput.stories.jsx
  src/styles/index.css
  tailwind.config.js
Labels: need review

#41 ✨[FORM] Ajout de la navigation dynamique dans le composant Form et mi…
  src/components/ui/Form.jsx
  src/pages/ConnexionForm.jsx
  src/pages/ForgotPasswordForm.jsx
  src/pages/UserForm.jsx
Labels: bug, dev

#47 ✨[INPUT, FORM] Enhance input validation and error handling in Input, …
  src/components/ui/Input.jsx
  src/pages/ForgotPasswordForm.jsx
  src/pages/UserForm.jsx
Labels: in progress, dev
